[package]
name = "cuttle_bin"
version = "0.1.0"
edition = "2024"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[[bin]]
name = "cuttle"
path = "src/bin/cuttle.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
tempfile = "3.0"
chrono = { version = "0.4", features = ["serde"] }
cuttle = { path = "../cuttle" }
cuttle_blender_api = { path = "../blender_api" }

[lints]
workspace = true
