[package]
name = "cuttle_lang"
version = "0.1.0"
edition = "2024"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[dependencies]
ariadne = "0.4"
chumsky = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true
